name: Github script

on:
  issues:
    type: [opened]

jobs:
  comment:
    name: comment on the issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 You've created this issue comment using GitHub Script!!!"
            })
            github.projects.createCard({
              coloumn_id: 18954780,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            })
